image: python:3.8-alpine

stages:
  - init

variables:
  GIT_STRATEGY: none

init-project:
  stage: init
  script:
    - exit
    - pwd
    - mkdir /home/projects
    - cd /home/projects
    - git clone ssh://git@gitlab.farakaft.ir/h.azarbad/similarity-bot.git
    - cd similarity-bot
    - docker-compose up -d