version: '3.1'

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: similarity_race_bot
    volumes:
    - .:/similarity_race_bot
    ports:
    - "1080:1080"

